### ISSUE TITLE
fail on unsafe integrity

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/obs-service-node_modules#26]
Make sure the integrity is maintained with hashes with safe algorithms provided by trusted user input and otherwise fail hard.

When I just skimmed the source to check how it deals with file hashes, it seems the default is currently unsafe. E.g. it sometimes generates hashes. Probably partly after https://github.com/openSUSE/obs-service-node_modules/issues/16 . But current node .lock files have good hashes. (These hashes are presently untrusted, but one thing after another.)

While a default off option to get the present behavior would be ok, maybe there is a better way? E.g. it might be preferable to have a file from the developer with hashes as a substitute for such cases, so that they can check these out of band. But I currently don't know why a .lock file would have no hashes.

**Comment by AdamMajer** [comment]
node_modules just assumes what we get from upstream is correct. The upstream (npm) has some optional integrity fields, including ones that are signed,

https://docs.npmjs.com/verifying-the-pgp-signature-for-a-package-from-the-npm-public-registry

The #16 is mostly about no integrity field at all present in the lock file. This integrity field comes from the upstream registry and is actually an optional field. All this depends on the state of what is published in npm. If it's not published, we can't really check for integrity aside from the OBS download_files way -- download it again and check if not changed ;)

So, we can check in cases these exist, but we can't really fail if they don't.

**Comment by JanZerebecki** [comment]
I do not see why we can not fail if they don't exist.
The developer can provide them if they want to, e.g. in an additional file or by forking the npm package. Or explicitly set a insecure-continue-without-hash option.

Thank you, about the link about signatures on npm.

**Comment by AdamMajer** [comment]
So, how do you fork that? There is currently no mechanism for maintenance of npm installed dependencies (or pip or rubygems). The solution is to have a maintenance proxy fed packages from us, but that requires some work for a PoC.

Regarding missing integrity field, it seems to happen when the actual dependency is not installed because it's bundled. But at the same time, `npm` will try to fetch the dependency info which comes from `package/package.json` of the bundled package. The current solution is to get tarballs of these bundled modules and serve the `package.json` though they are not then installed by `npm install` because they are already bundled. Maybe a better solution is to fetch the package.json from inside the bundled package in the `npm-localhost-proxy` but I haven't looked too closely into it. A note here: many packages include `package.json` in its subdirectories that have nothing to do with bundled dependencies but with their unit tests so this can be tricky.

**Comment by AdamMajer** [comment]
So, IFF integrity exists and it fails, then fail. IFF it doesn't exist, ignore would be better approach.

**Comment by JanZerebecki** [comment]
> So, how do you fork that?

It seems that is not needed. I don't think the npm index ever lacks them. But, if it was really a problem a specific module has and you can't convince its upstream to accept the fix for it, you would register a new name in npm.org and publish your fork to it.

> Regarding missing integrity field, it seems to happen when the actual dependency is not installed because it's bundled.

But if its already bundled upstream then the obs service isn't needed.
Do you have an example for a software that generates a .lock file with the integrity hash removed? Maybe we can get that fixed as the information should be available.
Or better a package that currently has this problem?

The problem in https://github.com/openSUSE/obs-service-node_modules/issues/16 probably has something to do with that upstream tryton-sao source does not have the .lock file committed. The index has the hash:
```
$ npm view align-text@0.1.4 dist.integrity
sha512-GrTZLRpmp6wIC2ztrWW9MjjTgSKccffgFagbNDOX95/dcjEcYZibYTeaOntySQLcdw1ztBoFkviiUvTMbb9MYg==
```
The source service should be able to get the information as it has access to the index.

**Comment by AdamMajer** [comment]
> It seems that is not needed. I don't think the npm index ever lacks them. But, if it was really a problem a specific module has and you can't convince its upstream to accept the fix for it, you would register a new name in npm.org and publish your fork to it.

Sure, but then the problem is for the dependency to switch to your new name or prefix. This is not how we create forks (patched software) for any distro.

> Do you have an example for a software that generates a .lock file with the integrity hash removed?

In that case it was tryton-sao. The package that generates that lock in simply npm and you run it with `npm install --package-lock-only --legacy-peer-deps --ignore-scripts` but I didn't write which version of tryton-sao was the issue .... it has something to do when packages are bundled inside another but not certain if it's still an issue today.

**Comment by JanZerebecki** [comment]
With https://github.com/tryton/sao at tag 4.2.0 I get in the lock file:
```
    "node_modules/align-text": {
      "version": "0.1.4",
      "resolved": "https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz",
      "integrity": "sha512-GrTZLRpmp6wIC2ztrWW9MjjTgSKccffgFagbNDOX95/dcjEcYZibYTeaOntySQLcdw1ztBoFkviiUvTMbb9MYg==",
      "dev": true,
      "dependencies": {
        "kind-of": "^3.0.2",
        "longest": "^1.0.1",
        "repeat-string": "^1.5.2"
      },
      "engines": {
        "node": ">=0.10.0"
      }
    },
```
Maybe something was fixed in npm. Seem like we are good to proceed.



> So, IFF integrity exists and it fails, then fail. IFF it doesn't exist, ignore would be better approach.

That makes it impossible to be used securely. This is a common security problem, see https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/ . Similarly an ssh server in its default configuration doesn't allow you access if the client says they don't support authentication.

To fix this, perhaps:
- IFF update-lock-file is set in _service to true, regenerate it
- IF the lock file is missing fail
- IFF integrity doesn't exist and insecure-continue-without-hash is set in _service to true, warn and proceed
- IFF integrity passes, proceed
otherwise fail

If someone encounters a problem like this again they can just patch the lock file to include the hash that they verified out of band or if they don't want to be bothered use the setting. In either way I'd prefer the issue would be reported and fixed as far upstream as possible.

Similarly for Factory the setting is easy to spot and can be automatically searched for. If it were to be allowed by default, it is easy to miss the issue and complicated to search for packages with it.
